BEGIN
    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Fiat 500', '1200cc', '15000km', 1, 'Mario Rossi', 1);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Volkswagen Golf', '1400cc', '30000km', 0, 'Luigi Bianchi', 2);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Toyota Yaris', '1000cc', '20000km', 1, 'Anna Verdi', 3);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Renault Clio', '1100cc', '25000km', 0, 'Carla Neri', 4);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Ford Fiesta', '1300cc', '18000km', 1, 'Paolo Gialli', 5);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('BMW 320i', '2000cc', '50000km', 0, 'Giulia Marroni', 6);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Audi A3', '1600cc', '40000km', 1, 'Luca Rossi', 7);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Mercedes-Benz C180', '1800cc', '45000km', 0, 'Sophia Blu', 8);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Opel Astra', '1500cc', '35000km', 1, 'Marco Viola', 9);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Peugeot 208', '1200cc', '22000km', 0, 'Laura Grigi', 10);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Hyundai i20', '1000cc', '14000km', 1, 'Franco Rosa', 11);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Kia Rio', '1400cc', '17000km', 0, 'Giada Celesti', 12);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Mazda 2', '1300cc', '21000km', 1, 'Fabio Dorati', 13);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Honda Civic', '2000cc', '33000km', 0, 'Elisa Zaffiro', 14);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Chevrolet Spark', '1200cc', '29000km', 1, 'Vincenzo Marroni', 15);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Skoda Fabia', '1000cc', '31000km', 0, 'Giorgia Rame', 16);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Dacia Sandero', '1300cc', '27000km', 1, 'Lucia Verde', 17);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Seat Ibiza', '1400cc', '35000km', 0, 'Andrea Oro', 18);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Suzuki Swift', '1100cc', '26000km', 1, 'Marta Turchese', 19);

    INSERT INTO SESAMO.MON_TEST (MODELLO, CILINDRATA, KILOMETRAGGIO, USATA, PROPRIETARIO, ID)
    VALUES ('Nissan Micra', '1200cc', '24000km', 0, 'Pietro Nero', 20);

    COMMIT;
   EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END;
